ExamApplication/Web/Areas/Administration/Controllers/UserAdministrationController.cs
using ExamApplication.Data.Models;
using ExamApplication.Services.Users;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExamApplication.Web.Areas.Administration.Controllers
{
    [Route("Administration/Users")]
    public class UserAdministrationController : BaseAdministrationController
    {
        private readonly IUserService service;


        /*private readonly UserManager<ExamApplicationUser> userManager;*/
        /*public UserAdministrationController(IUserService service, 
            UserManager<ExamApplicationUser> userManager)
        {
            this.service = service;
            this.userManager = userManager;
        }*/
        public UserAdministrationController(IUserService service)
        {
            this.service = service;
        }
        public ActionResult Index()
        {
            return View(this.service.GetAllUsers());
        }

        /*[HttpGet("/Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("/Create")]
        public async Task<IActionResult> Create(CategoryDto categoryDto)
        {
            categoryDto.CreatedBy = new ExamApplicationUserDto
            {
                Id = this.User.FindFirst(ClaimTypes.NameIdentifier).Value
            };
            await this.service.CreateCategory(categoryDto);
            return Redirect("/Administration/Categories");
        }
        [Route("Edit/{id}")]
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(long id)
        {
            *//*return View((await this.service.getCategoryById(id)).ToWebModel());*//*
            return View((await this.service.GetCategoryById(id)));
        }
    [Route("Edit/{id}")]
    [HttpPost("Edit/{id}")]
    public async Task<IActionResult> Edit(long id, CategoryDto categoryDto)
    {
        await this.service.UpdateCategory(id, categoryDto);

        return Redirect("/Administration/Categories");
    }
    [Route("/Delete/{id}")]
    public async Task<IActionResult> Delete(long id)
    {
        await this.service.DeleteCategory(id);

        return Redirect("/Administration/Categories");
    }*/
    [Route("Users/Delete/{id}")]
    public async Task<IActionResult> Delete(string id)
    {
        await this.service.DeleteUser(id);

        return Redirect("/Administration/Users");
    }
    }
}

ExamApplication/Web/Areas/Administration/Views/UserAdministration/Create.cshtml
@*@using ExamApplication.Service.Models.Users

@{
    Layout = "../Shared/_AdminLayout";
}
@model ExamApplicationUserDto
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <h2>Create user</h2>
    <form asp-area="Administration" asp-controller="PostAdministration" asp-action="Create" method="post">
      <div class="form-group">
        <label asp-for="Name" for="name">First Name</label>
        <input asp-for="Name" type="text" class="form-control mb-3" id="name" placeholder="First Name...">
      </div>
      <div class="form-group">
        <label asp-for="LastName" for="last-name">Last Name</label>
        <input asp-for="LastName" type="text" class="form-control mb-3" id="last-name" placeholder="Last Name...">
      </div>
      <div class="form-group">
        <label asp-for="Email" for="email">Last Name</label>
        <input asp-for="Email" type="email" class="form-control mb-3" id="email" placeholder="Email...">
      </div>
      <div class="form-group">
        <label asp-for="Password" for="password">Password</label>
        <input asp-for="Password" type="password" class="form-control mb-3" id="password" placeholder="Password...">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>
</html>*@

ExamApplication/Web/Areas/Administration/Views/UserAdministration/Edit.cshtml
@using ExamApplication.Service.Models.Users
@{
    Layout = "../Shared/_AdminLayout";
}
@model ExamApplicationUserDto
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <h2>Create user</h2>
    <form asp-area="Administration" asp-controller="PostAdministration" asp-action="Create" method="post">
      <div class="form-group">
        <label asp-for="Name" for="name">First Name</label>
        <input asp-for="Name" type="text" class="form-control mb-3" id="name" placeholder="First Name...">
      </div>
      <div class="form-group">
        <label asp-for="LastName" for="last-name">Last Name</label>
        <input asp-for="LastName" type="text" class="form-control mb-3" id="last-name" placeholder="Last Name...">
      </div>
      <div class="form-group">
        <label asp-for="Email" for="email">Last Name</label>
        <input asp-for="Email" type="email" class="form-control mb-3" id="email" placeholder="Email...">
      </div>
      <div class="form-group">
        <label asp-for="Password" for="password">Password</label>
        <input asp-for="Password" type="password" class="form-control mb-3" id="password" placeholder="Passwor...">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>
</html>

ExamApplication/Web/Areas/Administration/Views/UserAdministration/Index.cshtml
@using ExamApplication.Service.Models.Users
@{
    Layout = "../Shared/_AdminLayout";
}
@model List<ExamApplicationUserDto>
<h1>Users</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    @foreach(ExamApplicationUserDto user in Model)
        {
        <tr>
            <th>@(user.Id)</th>
            <td>@(user.Name)</td>
            <td>@(user.LastName)</td>
            <td>@(user.Email)</td>
            <td><a class="btn btn-primary" asp-area="Administration" asp-controller="UserAdministration" asp-action="Edit" asp-route-id="@user.Id">Edit</a></td>
            <td><a class="btn btn-primary" asp-area="Administration" asp-controller="UserAdministration" asp-action="Delete" asp-route-id="@user.Id">Delete</a></td>
        </tr>
        }
    <a class="btn btn-primary" asp-area="Identity" asp-page="/Account/Register">Create</a>
    </tbody>
</table>