ExamApplication/Web/Areas/Administration/Controllers/EventAdministrationController.cs
using ExamApplication.Service.Models.Events;
using ExamApplication.Service.Models.Users;
using ExamApplication.Services.Events;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ExamApplication.Web.Areas.Administration.Controllers
{
    [Route("Administration/Events")]
    public class EventAdministrationController : BaseAdministrationController
    {
        private readonly IEventService service;
        public EventAdministrationController(IEventService service)
        {
            this.service = service;
        }
        public IActionResult Index()
        {
            return View(this.service.GetAllEvents());
        }
        [HttpGet("Events/Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Events/Create")]
        public async Task<IActionResult> Create(EventDto eventDto)
        {
            eventDto.CreatedBy = new ExamApplicationUserDto
            {
                Id = this.User.FindFirst(ClaimTypes.NameIdentifier).Value
            };
            await this.service.CreateEvent(eventDto);
            return Redirect("/Administration/Events");
        }
        [Route("Events/Edit/{id}")]
        [HttpGet("Events/Edit/{id}")]
        public async Task<IActionResult> Edit(long id)
        {
            return View(await this.service.GetEventById(id));
        }
        [Route("Events/Edit/{id}")]
        [HttpPost("Events/Edit/{id}")]
        public async Task<IActionResult> Edit(long id, EventDto eventDto)
        {
            await this.service.UpdateEvent(id, eventDto);

            return Redirect("/Administration/Events");
        }
        [Route("Events/Delete/{id}")]
        public async Task<IActionResult> Delete(long id)
        {
            await this.service.DeleteEvent(id);

            return Redirect("/Administration/Events");
        }
    }
}

ExamApplication/Web/Areas/Administration/Views/EventAdministration/Create.cshtml
@using ExamApplication.Service.Models.Events
@{
    Layout = "../Shared/_AdminLayout";
}
@model EventDto
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
  <h2>Create Event</h2>
    <form asp-area="Administration" asp-controller="EventAdministration" asp-action="Create" method="post">
      <div class="form-group">
        <label asp-for="Name" for="name">Name</label>
        <input asp-for="Name" type="text" class="form-control mb-3" id="name" placeholder="Name...">
      </div>
      <div class="form-group">
        <label asp-for="Description" for="description">Description</label>
        <input asp-for="Description" type="text" class="form-control mb-3" id="description" placeholder="Description...">
      </div>
      <div class="form-group">
        <label asp-for="Date" for="date">Description</label>
        <input asp-for="Date" type="date" class="form-control mb-3" id="date" placeholder="Date...">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>
</html>

ExamApplication/Web/Areas/Administration/Views/EventAdministration/Edit.cshtml
@using ExamApplication.Service.Models.Events
@{
    Layout = "../Shared/_AdminLayout";
}
@model EventDto
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
  <h2>Create Event</h2>
    <form asp-area="Administration" asp-controller="EventAdministration" asp-action="Edit" method="post">
      <div class="form-group">
        <label asp-for="Name" for="name">Name</label>
        <input asp-for="Name" type="text" class="form-control mb-3" id="name" placeholder="Name...">
      </div>
      <div class="form-group">
        <label asp-for="Description" for="description">Description</label>
        <input asp-for="Description" type="text" class="form-control mb-3" id="description" placeholder="Description...">
      </div>
      <div class="form-group">
        <label asp-for="Date" for="date">Description</label>
        <input asp-for="Date" type="date" class="form-control mb-3" id="date" placeholder="Date...">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>
</html>

ExamApplication/Web/Areas/Administration/Views/EventAdministration/Index.cshtml
@using ExamApplication.Service.Models.Events
@using ExamApplication.Service.Models.Users
@{
    Layout = "../Shared/_AdminLayout";
}
@model List<EventDto>
<h1>Events</h1>
@foreach(EventDto eventDto in Model)
{
        <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="..." alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">@(eventDto.Name)</h5>
        <p class="card-text">@(eventDto.Description)</p>
        <p class="card-text">@(eventDto.Date)</p>
        <a class="btn btn-primary" asp-area="Administration" asp-controller="EventAdministration" asp-action="Edit" asp-route-id="@(eventDto.Id)">Edit</a>
        <a class="btn btn-primary" asp-area="Administration" asp-controller="EventAdministration" asp-action="Delete" asp-route-id="@(eventDto.Id)">Delete</a>
        <a href="#" class="btn btn-primary">Get a ticket</a>
      </div>
    </div>
}
<a class="btn btn-primary" asp-area="Administration" asp-controller="EventAdministration" asp-action="Create">Create Event</a>
</table>